services:
  nats_core:
    container_name: nats_core
    image: "bitnami/nats:latest"
    ports:
      - 4222:4222
    environment:
      - NATS_ENABLE_AUTH=yes
      - NATS_USERNAME=uvbcEWCVNTNHv5Hylk7MBYmRsnHKT5VixVOBJo
      - NATS_PASSWORD=gxvaXyuHXuktyGrMEzWtXQmaFw3szaasGnuQZ35
    volumes:
      - ./.opt/nats_core/logs:/etc/logs
      - ./.opt/nats_core/data:/bitnami/nats/data
    restart: unless-stopped
    networks:
      - wyrstream-dev
  redis:
    container_name: redis
    image: bitnami/redis:latest
    volumes:
      - ./.opt/redis_data:/bitnami/redis/data
    environment:
      - REDIS_PASSWORD=o0xN5KFkYKOiyhQkPZ384oVhCGDkfmr63a3zZdKX
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - wyrstream-dev
  minio:
    image: bitnami/minio:latest
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./.opt/minio_data:/bitnami/minio/data
    environment:
      - MINIO_ROOT_USER=OKqZVj08DLcj80fS7LuNYWw5ljsWQ8e0NcXv0q+h
      - MINIO_ROOT_PASSWORD=UJiQP8Q7ds72PuPv988WY42+2ZhBucefv6bPgwYY
      - MINIO_DEFAULT_BUCKETS=wyrstream
    restart: unless-stopped
    networks:
      - wyrstream-dev
networks:
  wyrstream-dev:
    driver: bridge